// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: sq_line_ST7789V3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Battery;
lv_obj_t * ui_Network;
lv_obj_t * ui_LittleFSUsed;
lv_obj_t * ui_SDCardFree;
lv_obj_t * ui_NetworkAddress;
lv_obj_t * ui_co2count;
lv_obj_t * ui_co2ppm;
lv_obj_t * ui_airQuality;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Pressure;
lv_obj_t * ui_Border;
lv_obj_t * ui_batteryVoltage;
lv_obj_t * ui_wifiDisabled;
lv_obj_t * ui_wifiApMode;
lv_obj_t * ui_wifiStaMode;
lv_obj_t * ui_BatteryFull;
lv_obj_t * ui_Battery80;
lv_obj_t * ui_BatteryHalf;
lv_obj_t * ui_BatteryLow;
lv_obj_t * ui_BatteryEmpty;
// CUSTOM VARIABLES
lv_obj_t * uic_Battery;
lv_obj_t * uic_Network;
lv_obj_t * uic_LittleFSUsed;
lv_obj_t * uic_SDCardFree;
lv_obj_t * uic_NetworkAddress;
lv_obj_t * uic_co2count;
lv_obj_t * uic_co2ppm;
lv_obj_t * uic_airQuality;
lv_obj_t * uic_Humidity;
lv_obj_t * uic_Temperature;
lv_obj_t * uic_Pressure;
lv_obj_t * uic_batteryVoltage;
lv_obj_t * uic_wifiDisabled;
lv_obj_t * uic_wifiApMode;
lv_obj_t * uic_wifiStaMode;
lv_obj_t * uic_BatteryFull;
lv_obj_t * uic_Battery80;
lv_obj_t * uic_BatteryHalf;
lv_obj_t * uic_BatteryLow;
lv_obj_t * uic_BatteryEmpty;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_simple_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
