// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: sq_line_ST7789V3

#ifndef _SQ_LINE_ST7789V3_UI_H
#define _SQ_LINE_ST7789V3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_Network;
extern lv_obj_t * ui_LittleFSUsed;
extern lv_obj_t * ui_SDCardFree;
extern lv_obj_t * ui_NetworkAddress;
extern lv_obj_t * ui_co2count;
extern lv_obj_t * ui_co2ppm;
extern lv_obj_t * ui_airQuality;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Pressure;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Battery;
extern lv_obj_t * uic_Network;
extern lv_obj_t * uic_LittleFSUsed;
extern lv_obj_t * uic_SDCardFree;
extern lv_obj_t * uic_NetworkAddress;
extern lv_obj_t * uic_co2count;
extern lv_obj_t * uic_co2ppm;
extern lv_obj_t * uic_airQuality;
extern lv_obj_t * uic_Humidity;
extern lv_obj_t * uic_Temperature;
extern lv_obj_t * uic_Pressure;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
