// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: sq_line_ST7789V3

#ifndef _SQ_LINE_ST7789V3_UI_H
#define _SQ_LINE_ST7789V3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_Network;
extern lv_obj_t * ui_LittleFSUsed;
extern lv_obj_t * ui_SDCardFree;
extern lv_obj_t * ui_NetworkAddress;
extern lv_obj_t * ui_co2count;
extern lv_obj_t * ui_co2ppm;
extern lv_obj_t * ui_airQuality;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Pressure;
extern lv_obj_t * ui_Border;
extern lv_obj_t * ui_batteryVoltage;
extern lv_obj_t * ui_wifiDisabled;
extern lv_obj_t * ui_wifiApMode;
extern lv_obj_t * ui_wifiStaMode;
extern lv_obj_t * ui_BatteryFull;
extern lv_obj_t * ui_Battery80;
extern lv_obj_t * ui_BatteryHalf;
extern lv_obj_t * ui_BatteryLow;
extern lv_obj_t * ui_BatteryEmpty;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Battery;
extern lv_obj_t * uic_Network;
extern lv_obj_t * uic_LittleFSUsed;
extern lv_obj_t * uic_SDCardFree;
extern lv_obj_t * uic_NetworkAddress;
extern lv_obj_t * uic_co2count;
extern lv_obj_t * uic_co2ppm;
extern lv_obj_t * uic_airQuality;
extern lv_obj_t * uic_Humidity;
extern lv_obj_t * uic_Temperature;
extern lv_obj_t * uic_Pressure;
extern lv_obj_t * uic_batteryVoltage;
extern lv_obj_t * uic_wifiDisabled;
extern lv_obj_t * uic_wifiApMode;
extern lv_obj_t * uic_wifiStaMode;
extern lv_obj_t * uic_BatteryFull;
extern lv_obj_t * uic_Battery80;
extern lv_obj_t * uic_BatteryHalf;
extern lv_obj_t * uic_BatteryLow;
extern lv_obj_t * uic_BatteryEmpty;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_15px_png);    // assets/wifi_15px.png
LV_IMG_DECLARE(ui_img_wifi_ap_x15_png);    // assets/wifi_ap_x15.png
LV_IMG_DECLARE(ui_img_1836401811);    // assets/wi-fi_sta_x15.png
LV_IMG_DECLARE(ui_img_battery_100_x16_png);    // assets/battery_100_x16.png
LV_IMG_DECLARE(ui_img_battery_80_x16_png);    // assets/battery_80_x16.png
LV_IMG_DECLARE(ui_img_battery_50_x16_png);    // assets/battery_50_x16.png
LV_IMG_DECLARE(ui_img_battery_10_x16_png);    // assets/battery_10_x16.png
LV_IMG_DECLARE(ui_img_battery_died_x16_png);    // assets/battery_died_x16.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
