// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Waveshare_LDC_172_320_v2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BatteryFull;
lv_obj_t * ui_Battery85;
lv_obj_t * ui_BatteryHalf;
lv_obj_t * ui_BatteryHalfLess;
lv_obj_t * ui_BatteryLow;
lv_obj_t * ui_batteryVoltage;
lv_obj_t * ui_batteryPercentage;
lv_obj_t * ui_WifiAP;
lv_obj_t * ui_NoWifi;
lv_obj_t * ui_WifiLocal;
lv_obj_t * ui_Co2Severity;
lv_obj_t * ui_Co2txtstatic;
lv_obj_t * ui_Co2Number;
lv_obj_t * ui_Co2Ppmstatic;
lv_obj_t * ui_AQIndexstatic;
lv_obj_t * ui_AQIndexNumber;
lv_obj_t * ui_AirPressureNumber;
lv_obj_t * ui_AirPressureStatic;
lv_obj_t * ui_TemperatureBar;
lv_obj_t * ui_HumidityBar;
lv_obj_t * ui_TempHumidityPic;
lv_obj_t * ui_TemperatureNumber;
lv_obj_t * ui_HumidityNumber;
lv_obj_t * ui_UsersConnected;
lv_obj_t * ui_NetworkAddress;
lv_obj_t * ui_LfsUsed;
lv_obj_t * ui_SdCardFree;
lv_obj_t * ui_AIR;
lv_obj_t * ui_Danger;
lv_obj_t * ui_Warning;
// CUSTOM VARIABLES
lv_obj_t * uic_BatteryFull;
lv_obj_t * uic_Battery85;
lv_obj_t * uic_BatteryHalf;
lv_obj_t * uic_batteryVoltage;
lv_obj_t * uic_batteryPercentage;
lv_obj_t * uic_WifiAP;
lv_obj_t * uic_NoWifi;
lv_obj_t * uic_WifiLocal;
lv_obj_t * uic_Co2Severity;
lv_obj_t * uic_Co2txtstatic;
lv_obj_t * uic_Co2Number;
lv_obj_t * uic_Co2Ppmstatic;
lv_obj_t * uic_AQIndexstatic;
lv_obj_t * uic_AQIndexNumber;
lv_obj_t * uic_AirPressureNumber;
lv_obj_t * uic_TemperatureBar;
lv_obj_t * uic_HumidityBar;
lv_obj_t * uic_TempHumidityPic;
lv_obj_t * uic_UsersConnected;
lv_obj_t * uic_NetworkAddress;
lv_obj_t * uic_LfsUsed;
lv_obj_t * uic_SdCardFree;
lv_obj_t * uic_Danger;
lv_obj_t * uic_Warning;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
