// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Waveshare_LDC_172_320_v2

#ifndef _WAVESHARE_LDC_172_320_V2_UI_H
#define _WAVESHARE_LDC_172_320_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BatteryFull;
extern lv_obj_t * ui_Battery85;
extern lv_obj_t * ui_BatteryHalf;
extern lv_obj_t * ui_BatteryHalfLess;
extern lv_obj_t * ui_BatteryLow;
extern lv_obj_t * ui_batteryVoltage;
extern lv_obj_t * ui_batteryPercentage;
extern lv_obj_t * ui_WifiAP;
extern lv_obj_t * ui_NoWifi;
extern lv_obj_t * ui_WifiLocal;
extern lv_obj_t * ui_Co2Severity;
extern lv_obj_t * ui_Co2txtstatic;
extern lv_obj_t * ui_Co2Number;
extern lv_obj_t * ui_Co2Ppmstatic;
extern lv_obj_t * ui_AQIndexstatic;
extern lv_obj_t * ui_AQIndexNumber;
extern lv_obj_t * ui_AirPressureNumber;
extern lv_obj_t * ui_AirPressureStatic;
extern lv_obj_t * ui_TemperatureBar;
extern lv_obj_t * ui_HumidityBar;
extern lv_obj_t * ui_TempHumidityPic;
extern lv_obj_t * ui_TemperatureNumber;
extern lv_obj_t * ui_HumidityNumber;
extern lv_obj_t * ui_UsersConnected;
extern lv_obj_t * ui_NetworkAddress;
extern lv_obj_t * ui_LfsUsed;
extern lv_obj_t * ui_SdCardFree;
extern lv_obj_t * ui_AIR;
extern lv_obj_t * ui_Danger;
extern lv_obj_t * ui_Warning;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BatteryFull;
extern lv_obj_t * uic_Battery85;
extern lv_obj_t * uic_BatteryHalf;
extern lv_obj_t * uic_batteryVoltage;
extern lv_obj_t * uic_batteryPercentage;
extern lv_obj_t * uic_WifiAP;
extern lv_obj_t * uic_NoWifi;
extern lv_obj_t * uic_WifiLocal;
extern lv_obj_t * uic_Co2Severity;
extern lv_obj_t * uic_Co2txtstatic;
extern lv_obj_t * uic_Co2Number;
extern lv_obj_t * uic_Co2Ppmstatic;
extern lv_obj_t * uic_AQIndexstatic;
extern lv_obj_t * uic_AQIndexNumber;
extern lv_obj_t * uic_AirPressureNumber;
extern lv_obj_t * uic_TemperatureBar;
extern lv_obj_t * uic_HumidityBar;
extern lv_obj_t * uic_TempHumidityPic;
extern lv_obj_t * uic_UsersConnected;
extern lv_obj_t * uic_NetworkAddress;
extern lv_obj_t * uic_LfsUsed;
extern lv_obj_t * uic_SdCardFree;
extern lv_obj_t * uic_Danger;
extern lv_obj_t * uic_Warning;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_batt_full_x32_png);    // assets/Batt_full_x32.png
LV_IMG_DECLARE(ui_img_batt_85_x32_png);    // assets/Batt_85_x32.png
LV_IMG_DECLARE(ui_img_batt_half_x32_png);    // assets/Batt_half_x32.png
LV_IMG_DECLARE(ui_img_batt_half_less_x32_png);    // assets/Batt_half_less_x32.png
LV_IMG_DECLARE(ui_img_batt_low_x32_png);    // assets/Batt_low_x32.png
LV_IMG_DECLARE(ui_img_signal_x32_png);    // assets/signal_x32.png
LV_IMG_DECLARE(ui_img_806973588);    // assets/no-wifi_x32.png
LV_IMG_DECLARE(ui_img_wifi_x32_png);    // assets/wifi_x32.png
LV_IMG_DECLARE(ui_img_risk_165_142_png);    // assets/risk_165_142.png
LV_IMG_DECLARE(ui_img_599688048);    // assets/Cold-to_hot_x125_x10.png
LV_IMG_DECLARE(ui_img_1680534988);    // assets/Dry-to-wet_x125_x10.png
LV_IMG_DECLARE(ui_img_humidity4_x32_png);    // assets/humidity4_x32.png
LV_IMG_DECLARE(ui_img_air2_x32_png);    // assets/air2_x32.png
LV_IMG_DECLARE(ui_img_danger_x36_png);    // assets/danger_x36.png
LV_IMG_DECLARE(ui_img_warning_x36_png);    // assets/warning_x36.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
