// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: sq_line_ST7789V3

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Battery, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Battery, "500mV");
    lv_obj_set_style_text_align(ui_Battery, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Battery, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Network = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Network, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Network, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Network, "Wifi");
    lv_obj_set_style_text_align(ui_Network, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Network, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LittleFSUsed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LittleFSUsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LittleFSUsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LittleFSUsed, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LittleFSUsed, "20Kb");
    lv_obj_set_style_text_align(ui_LittleFSUsed, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LittleFSUsed, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardFree = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SDCardFree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDCardFree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDCardFree, 30);
    lv_obj_set_y(ui_SDCardFree, 0);
    lv_obj_set_align(ui_SDCardFree, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SDCardFree, "58Gb");
    lv_obj_set_style_text_align(ui_SDCardFree, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SDCardFree, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkAddress = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NetworkAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetworkAddress, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_NetworkAddress, "192.168.1.1");
    lv_obj_set_style_text_align(ui_NetworkAddress, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkAddress, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2count = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_co2count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_co2count, -1);
    lv_obj_set_y(ui_co2count, -10);
    lv_obj_set_align(ui_co2count, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_co2count, "2000");
    lv_obj_set_style_text_align(ui_co2count, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_co2count, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_co2ppm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_co2ppm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_co2ppm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_co2ppm, -1);
    lv_obj_set_y(ui_co2ppm, -1);
    lv_obj_set_align(ui_co2ppm, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_co2ppm, "ppm");
    lv_obj_set_style_text_font(ui_co2ppm, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airQuality = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_airQuality, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_airQuality, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_airQuality, 0);
    lv_obj_set_y(ui_airQuality, -10);
    lv_obj_set_align(ui_airQuality, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_airQuality, "AQI 88");
    lv_obj_set_style_text_align(ui_airQuality, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_airQuality, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 1);
    lv_obj_set_y(ui_Humidity, 2);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Humidity, "100%");
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 1);
    lv_obj_set_y(ui_Temperature, -12);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Temperature, "35C");
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Pressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pressure, 1);
    lv_obj_set_y(ui_Pressure, 14);
    lv_obj_set_align(ui_Pressure, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Pressure, "992hpa");
    lv_obj_set_style_text_align(ui_Pressure, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Battery = ui_Battery;
    uic_Network = ui_Network;
    uic_LittleFSUsed = ui_LittleFSUsed;
    uic_SDCardFree = ui_SDCardFree;
    uic_NetworkAddress = ui_NetworkAddress;
    uic_co2count = ui_co2count;
    uic_co2ppm = ui_co2ppm;
    uic_airQuality = ui_airQuality;
    uic_Humidity = ui_Humidity;
    uic_Temperature = ui_Temperature;
    uic_Pressure = ui_Pressure;

}
