#pragma once
#include <string.h>
#include "esp_log.h"


#ifdef CONNECTTION_SPI
#define DISP_SPI_SCLK CONFIG_DISP_GPIO_SCLK
#define DISP_SPI_MOSI CONFIG_DISP_GPIO_MOSI
#define DISP_SPI_RST CONFIG_DISP_GPIO_RST
#define DISP_SPI_DC CONFIG_DISP_GPIO_DC
#define DISP_SPI_CS CONFIG_DISP_GPIO_CS
#define DISP_SPI_BL CONFIG_DISP_GPIO_BL
#elif CONNECTTION_I2C
#define DISP_I2C_SDA DISP_I2C_SDA
#define DISP_I2C_SCL DISP_I2C_SCL
#define DISP_I2C_ADR DISP_I2C_ADR
#endif


void display_driver(void);
