// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Waveshare_LDC_172_320_v2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryFull = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BatteryFull, &ui_img_batt_full_x32_png);
    lv_obj_set_width(ui_BatteryFull, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryFull, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryFull, -3);
    lv_obj_set_y(ui_BatteryFull, 2);
    lv_obj_set_align(ui_BatteryFull, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BatteryFull, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatteryFull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery85 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Battery85, &ui_img_batt_85_x32_png);
    lv_obj_set_width(ui_Battery85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery85, -3);
    lv_obj_set_y(ui_Battery85, 2);
    lv_obj_set_align(ui_Battery85, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Battery85, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Battery85, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryHalf = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BatteryHalf, &ui_img_batt_half_x32_png);
    lv_obj_set_width(ui_BatteryHalf, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryHalf, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryHalf, -3);
    lv_obj_set_y(ui_BatteryHalf, 2);
    lv_obj_set_align(ui_BatteryHalf, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BatteryHalf, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatteryHalf, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryHalfLess = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BatteryHalfLess, &ui_img_batt_half_less_x32_png);
    lv_obj_set_width(ui_BatteryHalfLess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryHalfLess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryHalfLess, -3);
    lv_obj_set_y(ui_BatteryHalfLess, 2);
    lv_obj_set_align(ui_BatteryHalfLess, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BatteryHalfLess, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatteryHalfLess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryLow = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BatteryLow, &ui_img_batt_low_x32_png);
    lv_obj_set_width(ui_BatteryLow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLow, -3);
    lv_obj_set_y(ui_BatteryLow, 2);
    lv_obj_set_align(ui_BatteryLow, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BatteryLow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatteryLow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryVoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batteryVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryVoltage, -70);
    lv_obj_set_y(ui_batteryVoltage, 4);
    lv_obj_set_align(ui_batteryVoltage, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_batteryVoltage, "2555mV");
    lv_obj_set_style_text_color(ui_batteryVoltage, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batteryVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_batteryVoltage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batteryVoltage, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryPercentage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batteryPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryPercentage, -37);
    lv_obj_set_y(ui_batteryPercentage, 4);
    lv_obj_set_align(ui_batteryPercentage, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_batteryPercentage, "100%");
    lv_obj_set_style_text_color(ui_batteryPercentage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batteryPercentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_batteryPercentage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batteryPercentage, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiAP = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_WifiAP, &ui_img_signal_x32_png);
    lv_obj_set_width(ui_WifiAP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiAP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiAP, 2);
    lv_obj_set_y(ui_WifiAP, 1);
    lv_obj_add_flag(ui_WifiAP, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiAP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoWifi = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_NoWifi, &ui_img_806973588);
    lv_obj_set_width(ui_NoWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NoWifi, 3);
    lv_obj_set_y(ui_NoWifi, 1);
    lv_obj_add_flag(ui_NoWifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NoWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLocal = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_WifiLocal, &ui_img_wifi_x32_png);
    lv_obj_set_width(ui_WifiLocal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLocal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLocal, 4);
    lv_obj_set_y(ui_WifiLocal, 3);
    lv_obj_add_flag(ui_WifiLocal, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiLocal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Co2Severity = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Co2Severity, 150);
    lv_obj_set_height(ui_Co2Severity, 150);
    lv_obj_set_x(ui_Co2Severity, 3);
    lv_obj_set_y(ui_Co2Severity, 5);
    lv_obj_set_align(ui_Co2Severity, LV_ALIGN_LEFT_MID);
    lv_arc_set_range(ui_Co2Severity, 0, 2000);
    lv_arc_set_value(ui_Co2Severity, 2000);
    lv_obj_set_style_arc_color(ui_Co2Severity, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Co2Severity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Co2Severity, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Co2Severity, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Co2Severity, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_Co2Severity, &ui_img_risk_165_142_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Co2Severity, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Co2Severity, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Co2Severity, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Co2txtstatic = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Co2txtstatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2txtstatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2txtstatic, 48);
    lv_obj_set_y(ui_Co2txtstatic, -21);
    lv_obj_set_align(ui_Co2txtstatic, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Co2txtstatic, "CO2");
    lv_obj_set_style_text_color(ui_Co2txtstatic, lv_color_hex(0xA24200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2txtstatic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Co2txtstatic, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2txtstatic, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Number = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Co2Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Number, 35);
    lv_obj_set_y(ui_Co2Number, 10);
    lv_obj_set_align(ui_Co2Number, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Co2Number, "1898");
    lv_obj_set_style_text_align(ui_Co2Number, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2Number, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Ppmstatic = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Co2Ppmstatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Ppmstatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Ppmstatic, -82);
    lv_obj_set_y(ui_Co2Ppmstatic, 36);
    lv_obj_set_align(ui_Co2Ppmstatic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Ppmstatic, "ppm");
    lv_obj_set_style_text_color(ui_Co2Ppmstatic, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2Ppmstatic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQIndexstatic = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AQIndexstatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQIndexstatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQIndexstatic, 12);
    lv_obj_set_y(ui_AQIndexstatic, -29);
    lv_obj_set_align(ui_AQIndexstatic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQIndexstatic, "AQI");
    lv_obj_set_style_text_color(ui_AQIndexstatic, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQIndexstatic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AQIndexstatic, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQIndexstatic, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQIndexNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AQIndexNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQIndexNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQIndexNumber, 49);
    lv_obj_set_y(ui_AQIndexNumber, -28);
    lv_obj_set_align(ui_AQIndexNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQIndexNumber, "99");
    lv_obj_set_style_text_align(ui_AQIndexNumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQIndexNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirPressureNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AirPressureNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirPressureNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirPressureNumber, 14);
    lv_obj_set_y(ui_AirPressureNumber, -6);
    lv_obj_set_align(ui_AirPressureNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirPressureNumber, "993");
    lv_obj_set_style_text_align(ui_AirPressureNumber, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AirPressureNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirPressureStatic = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AirPressureStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirPressureStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirPressureStatic, 54);
    lv_obj_set_y(ui_AirPressureStatic, -6);
    lv_obj_set_align(ui_AirPressureStatic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirPressureStatic, "hpa");
    lv_obj_set_style_text_color(ui_AirPressureStatic, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AirPressureStatic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AirPressureStatic, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AirPressureStatic, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIR = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_AIR, &ui_img_air2_x32_png);
    lv_obj_set_width(ui_AIR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIR, 25);
    lv_obj_set_y(ui_AIR, -53);
    lv_obj_set_align(ui_AIR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AIR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureBar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_TemperatureBar, 0, 40);
    lv_bar_set_value(ui_TemperatureBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TemperatureBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TemperatureBar, 15);
    lv_obj_set_height(ui_TemperatureBar, 90);
    lv_obj_set_x(ui_TemperatureBar, -63);
    lv_obj_set_y(ui_TemperatureBar, -2);
    lv_obj_set_align(ui_TemperatureBar, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_TemperatureBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_TemperatureBar, &ui_img_599688048, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_TemperatureBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemperatureBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TemperatureBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TemperatureBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperatureBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemperatureBar, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TemperatureBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TemperatureBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TemperatureBar,
                                                                                                     lv_obj_get_style_pad_right(ui_TemperatureBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_HumidityBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_HumidityBar, 35, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HumidityBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HumidityBar, 15);
    lv_obj_set_height(ui_HumidityBar, 90);
    lv_obj_set_x(ui_HumidityBar, -10);
    lv_obj_set_y(ui_HumidityBar, -2);
    lv_obj_set_align(ui_HumidityBar, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_HumidityBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_HumidityBar, &ui_img_1680534988, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_HumidityBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumidityBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HumidityBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumidityBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HumidityBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HumidityBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumidityBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HumidityBar, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumidityBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_HumidityBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_HumidityBar,
                                                                                                  lv_obj_get_style_pad_right(ui_HumidityBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TempHumidityPic = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_TempHumidityPic, &ui_img_humidity4_x32_png);
    lv_obj_set_width(ui_TempHumidityPic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempHumidityPic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempHumidityPic, -27);
    lv_obj_set_y(ui_TempHumidityPic, -7);
    lv_obj_set_align(ui_TempHumidityPic, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_TempHumidityPic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TempHumidityPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureNumber, -58);
    lv_obj_set_y(ui_TemperatureNumber, -20);
    lv_obj_set_align(ui_TemperatureNumber, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_TemperatureNumber, "35");
    lv_obj_set_style_text_align(ui_TemperatureNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityNumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumidityNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityNumber, -6);
    lv_obj_set_y(ui_HumidityNumber, -20);
    lv_obj_set_align(ui_HumidityNumber, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_HumidityNumber, "35");
    lv_obj_set_style_text_align(ui_HumidityNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UsersConnected = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_UsersConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UsersConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UsersConnected, 12);
    lv_obj_set_y(ui_UsersConnected, 25);
    lv_label_set_text(ui_UsersConnected, "88");
    lv_obj_add_flag(ui_UsersConnected, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_UsersConnected, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UsersConnected, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkAddress = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NetworkAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkAddress, 4);
    lv_obj_set_y(ui_NetworkAddress, -2);
    lv_obj_set_align(ui_NetworkAddress, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_NetworkAddress, "192.168.8.8");
    lv_obj_set_style_text_color(ui_NetworkAddress, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkAddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NetworkAddress, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LfsUsed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LfsUsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LfsUsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LfsUsed, 0);
    lv_obj_set_y(ui_LfsUsed, -2);
    lv_obj_set_align(ui_LfsUsed, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LfsUsed, "LFS: 32KB");
    lv_obj_set_style_text_color(ui_LfsUsed, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LfsUsed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LfsUsed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SdCardFree = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SdCardFree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SdCardFree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SdCardFree, -4);
    lv_obj_set_y(ui_SdCardFree, -2);
    lv_obj_set_align(ui_SdCardFree, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_SdCardFree, "SD: 58GB");
    lv_obj_set_style_text_color(ui_SdCardFree, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SdCardFree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SdCardFree, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Danger = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Danger, &ui_img_danger_x36_png);
    lv_obj_set_width(ui_Danger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Danger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Danger, 31);
    lv_obj_set_y(ui_Danger, 33);
    lv_obj_set_align(ui_Danger, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Danger, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Danger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Warning = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Warning, &ui_img_warning_x36_png);
    lv_obj_set_width(ui_Warning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Warning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Warning, 31);
    lv_obj_set_y(ui_Warning, 33);
    lv_obj_set_align(ui_Warning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Warning, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Warning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_BatteryFull = ui_BatteryFull;
    uic_Battery85 = ui_Battery85;
    uic_BatteryHalf = ui_BatteryHalf;
    uic_batteryVoltage = ui_batteryVoltage;
    uic_batteryPercentage = ui_batteryPercentage;
    uic_WifiAP = ui_WifiAP;
    uic_NoWifi = ui_NoWifi;
    uic_WifiLocal = ui_WifiLocal;
    uic_Co2Severity = ui_Co2Severity;
    uic_Co2txtstatic = ui_Co2txtstatic;
    uic_Co2Number = ui_Co2Number;
    uic_Co2Ppmstatic = ui_Co2Ppmstatic;
    uic_AQIndexstatic = ui_AQIndexstatic;
    uic_AQIndexNumber = ui_AQIndexNumber;
    uic_AirPressureNumber = ui_AirPressureNumber;
    uic_TemperatureBar = ui_TemperatureBar;
    uic_HumidityBar = ui_HumidityBar;
    uic_TempHumidityPic = ui_TempHumidityPic;
    uic_UsersConnected = ui_UsersConnected;
    uic_NetworkAddress = ui_NetworkAddress;
    uic_LfsUsed = ui_LfsUsed;
    uic_SdCardFree = ui_SdCardFree;
    uic_Danger = ui_Danger;
    uic_Warning = ui_Warning;

}
